name: Code Checker
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
    paths:
      - 'revive.toml'
      - '.github/workflows/revive-lint.yml'

jobs:

  lint:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.1

    - name: Run Test Coverage
      run: 	go test -v -cover ./...

    - name: Run Revive Action
      uses: docker://morphy/revive-action:v2
      with:
        config: revive.toml

    - name: Check formatting
      run: gofmt -l .
